from collections import Counter
import itertools
import re

def prepare_text(text):
    text = re.sub(r'[^A-Za-z]', '', text.upper())
    text = text.replace('J', 'I')
    return text

def get_digrams(text):
    return [text[i:i+2] for i in range(0, len(text), 2)]

def analyze_frequency(ciphertext):
    ciphertext = prepare_text(ciphertext)
    digrams = get_digrams(ciphertext)
    freq = Counter(digrams)
    total = len(digrams)
    
    print("Top 20 Digram Frequencies:")
    for digram, count in freq.most_common(20):
        print(f"{digram}: {count/total:.2%}")

def decrypt_playfair(ciphertext, key):
    # Implementasi dekripsi Playfair
    pass

# Contoh penggunaan
ciphertext = """DCXQCQAIIUFZGRBIIBTKGSTBWCOIQCDNNGTINEDQSOGKRPENTNPOQMNGTIGVGL
BPRSCEMNGZRSXSKGCSMCPNTKBFHRSNVTSXBIQDESNVNSPCRMEQDPMNDXWCCBXR
EFFVIBKOIGTIDMKFGLWCFEIKFCISLIPSNYNFEWHRKGHQCESUPEKGCKPOIKVGDN
OAGNXQCWCQDWBLUIGCRNMKSITVCGIKIMWCKCGZDIIBKOIGFGKCRLGWQNQRISUE
RNNFKDENUMBIPESHNBCWHMGLPEDCXQNGPCRKCWIVLSSIRPMAIUMNRNGKRPLIDU
XDXBCOBIXNNFGNRGOQWCKGTNDNGWQNQRISUEWGBPSGLIDGSASNPNLGIBKOIGFG
KRLEDNPOMNFNBNZQCEDIPSEPEDZGRGTINBEFRGITBTRZWCOIQRISPVPSTIDICW
GCISERNGPCSKRMQFZRIDNFGLNESQFNDUBRAMKDSRPKGNNFGLNEASIDNEAMEYEG
NRPEFQWCEFNFNKNERTGWQNQRISUERNZMCTDISHSNGNNPRGLINFRHDCXQCQAIIU
EALRDNOAGNXGIBGLSHNSABFEKFCWQADAGAWCPMLVGKBFUSNGKRNMCWQDRSCEDQ
SOSKIKSKVGGRCQPEAMIDDWOQNSIKNDXRKFBIIBTKGSBLDNOAGNXQIGTNNXNBRM
QFPEIDTVNERQCIHIRMKIMBHIIVAMOQNGPCRMEPQDKFPIHISCXFTNGWQNRPLPFN
DUBRKFGKSPOIMWFEMQPCRGOQNBAMMLNGKQNGPCNRUEDIRGGLBFMNGZHGGINRUE
DINECGWOOKFENEKFFNDKPEKQGWPKNSNHOPCPSKUESHFNRNNRUEDIIMKSGQSGID
TNGWQNIMSGIRQDNBNYNFIRMANEASZNFXGMZKIDUSNATIDGFPPHTNZGKITVRGLV
WCFEGEEGKOCKZDSNPNCYSRPCNDDWLIREDIFESRGAENEGKRTKRHZSTNBPPELQWO
DITNGWQNIKSKVGGRNFKDENUMBIKRLEIDKHMNGZHGGIPEDCXQNGPCFVPIMNPRNG
TIERAISUDGFPPHTNWFGRCGSEQKRPLIIKOCDNPCGLAONKNETFBFNHVGUMSIFNEA
AMCEDIRLWCBIGHPKHRPBTKSKDWTNPXNGTNPCNFOQWCSIWTGWQNQRISUEGFAOBI
DNOAGNWFPXPEBRCPCQTCWQLIDNIDTWHMKGBLPWPCGLCWTIUSKFBPGKRNSKOINE
NRMNBIIKODPOQMKGNGPCSKNEHFSRSESNGNZY"""

analyze_frequency(ciphertext)

# Setelah analisis, gunakan kunci yang ditemukan
key = "CYBERFOX"
plaintext = decrypt_playfair(ciphertext, key)
print("\nDecrypted Plaintext (partial):")
print(plaintext[:200] + "...")